name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *"  # cada 12 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
